from plotly.io import to_html


def export_dashboard_html(figures: dict) -> str:
    """
    Export multiple Plotly figures into a styled, standalone HTML dashboard.
    """

    html_parts = []

    # ---------- HTML HEADER ----------
    html_parts.append("""
    <html>
    <head>
        <title>Data Visualization Dashboard</title>
        <meta charset="utf-8">

        <style>
            body {
                font-family: "Segoe UI", Arial, sans-serif;
                background-color: #f4f6f9;
                margin: 0;
                padding: 40px;
                color: #2c3e50;
            }

            h1 {
                text-align: center;
                color: #1f4fd8;
                margin-bottom: 40px;
            }

            .dashboard {
                max-width: 1200px;
                margin: auto;
            }

            .chart-card {
                background-color: #ffffff;
                padding: 25px;
                margin-bottom: 40px;
                border-radius: 12px;
                box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
            }

            .chart-title {
                font-size: 1.2rem;
                font-weight: 600;
                margin-bottom: 15px;
                color: #34495e;
            }

            footer {
                text-align: center;
                margin-top: 60px;
                font-size: 0.9rem;
                color: #7f8c8d;
            }
        </style>
    </head>

    <body>
        <h1>Automated Data Visualization Dashboard</h1>
        <div class="dashboard">
    """)

    # ---------- CHARTS ----------
    first = True
    for name, fig in figures.items():
        fig.update_layout(
            template="plotly_white",
            colorway=[
                "#1f77b4", "#ff7f0e", "#2ca02c",
                "#d62728", "#9467bd", "#8c564b"
            ],
            margin=dict(t=60, b=40, l=40, r=40),
        )

        html_parts.append("<div class='chart-card'>")
        html_parts.append(
            to_html(
                fig,
                include_plotlyjs="cdn" if first else False,
                full_html=False
            )
        )
        html_parts.append("</div>")

        first = False

    # ---------- FOOTER ----------
    html_parts.append("""
        </div>
        <footer>
            Generated by Automated Data Analysis Tool By Vishank Tyagi
        </footer>
    </body>
    </html>
    """)

    return "\n".join(html_parts)
